version: '3.1'
services: 
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
    ports:
      - "3306:3306"